version: '3.8'

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'change-this-password'
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - "8222:80"
    volumes:
      - ./vaultwarden:/data
    environment:
      - WEBSOCKET_ENABLED=true
    restart: unless-stopped

#  hastypaste:
 #   image: ghcr.io/0xerr0r/hasty-paste:latest
  #  container_name: hastypaste
  #  ports:
 #     - 9999:8080
#    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    ports:
      - 9000:9000
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8081
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./radarr/config:/config
      - ./qbittorrent/downloads:/downloads
      - ./jellyfin/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  dashy:
    image: lissy93/dashy
    container_name: dashy
    ports:
      - 8089:8080  # Maps localhost:8089 to Dashy's port 8080
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  custom-dashboard:
    image: nginx:alpine
    container_name: custom-dashboard
    volumes:
      - ./custom-dashboard:/usr/share/nginx/html:ro
    ports:
      - 8899:80
    restart: unless-stopped

  telemetry-api:
    build: ./stats-api
    container_name: stats-api
    ports:
      - "1337:1337"
    restart: unless-stopped
